# Generated by Django 5.0 on 2025-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("purple", "Purple"),
                ],
                default="light",
                help_text="Visual theme for the site",
                max_length=20,
            ),
        ),
    ]
