# Generated by Django 5.0 on 2025-11-24 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_sitesetting_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="button_text_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_bg_color",
            field=models.CharField(
                default="#0f172a",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_text_color",
            field=models.CharField(
                default="#cbd5e1",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_end_color",
            field=models.CharField(
                default="#6f42c1",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_start_color",
            field=models.CharField(
                default="#0d6efd",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_text_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="nav_bg_color",
            field=models.CharField(
                default="#0b1220",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="nav_text_color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="page_bg_color",
            field=models.CharField(
                default="#f8fafc",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="primary_color",
            field=models.CharField(
                default="#0d6efd",
                help_text="Primary brand color (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="text_color",
            field=models.CharField(
                default="#0f172a",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("purple", "Purple"),
                ],
                default="light",
                help_text="Visual theme preset",
                max_length=20,
            ),
        ),
    ]
