# Generated by Django 5.0 on 2025-11-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.CharField(default='general', help_text='Category label, e.g. general/finance/marketing.', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='If true, this resume is the primary one for its category.'),
        ),
    ]
