# Generated by Django 5.0 on 2026-02-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_resume_category_resume_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="resume_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a resume PDF for site-wide download link",
                null=True,
                upload_to="resumes/",
            ),
        ),
    ]
