# Generated by Django 5.0 on 2026-02-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_sitesetting_resume_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="preview_pdf",
            field=models.FileField(
                blank=True,
                help_text="Optional PDF for inline preview (use when main file is DOCX)",
                null=True,
                upload_to="resumes/previews/",
            ),
        ),
    ]
