# Generated by Django 5.0 on 2026-02-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_resume_preview_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="alternate_file",
            field=models.FileField(
                blank=True,
                help_text="Optional second format (e.g. DOCX if main is PDF, or vice versa)",
                null=True,
                upload_to="resumes/",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(
                help_text="Primary resume file (PDF or DOCX)", upload_to="resumes/"
            ),
        ),
    ]
