# Generated by Django 5.0 on 2026-02-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_resume_alternate_file_alter_resume_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True, help_text="Live demo / deployed URL"),
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers appear first"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="repo_url",
            field=models.URLField(
                blank=True, help_text="GitHub / source repository URL"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated technologies, e.g. Python, Django, PostgreSQL",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Uncheck to hide from public pages"
            ),
        ),
    ]
