# Generated by Django 5.0 on 2026-02-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_project_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="bio_long",
            field=models.TextField(blank=True, help_text="Full bio for the About page"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="bio_short",
            field=models.CharField(
                blank=True,
                help_text="One-liner for cards and meta descriptions",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="full_name",
            field=models.CharField(
                blank=True, help_text="Your display name", max_length=180
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="github_url",
            field=models.URLField(blank=True, help_text="GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="headline",
            field=models.CharField(
                blank=True,
                help_text="Short tagline, e.g. 'Data Analyst | Python Developer'",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="headshot",
            field=models.ImageField(
                blank=True,
                help_text="Professional headshot photo",
                null=True,
                upload_to="site/headshot/",
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
    ]
