# Generated by Django 5.0 on 2026-02-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_sitesetting_personal_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="motion_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable CSS animations and transitions"
            ),
        ),
    ]
