# Generated by Django 5.0 on 2026-02-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_sitesetting_motion_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="default_image_fit",
            field=models.CharField(
                choices=[
                    ("cover", "Cover (fill, crop edges)"),
                    ("contain", "Contain (fit inside, letterbox)"),
                ],
                default="cover",
                help_text="Default object-fit for images",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="default_image_ratio",
            field=models.CharField(
                choices=[
                    ("square", "Square (1:1)"),
                    ("landscape", "Landscape (4:3)"),
                    ("wide", "Wide (16:9)"),
                    ("ultrawide", "Ultrawide (21:9)"),
                    ("portrait", "Portrait (4:5)"),
                ],
                default="landscape",
                help_text="Default aspect ratio for images site-wide",
                max_length=20,
            ),
        ),
    ]
