# Generated by Django 5.0 on 2026-02-11 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_sitesetting_image_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Slug-like key, e.g. hero, card, portrait",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "aspect_ratio",
                    models.CharField(
                        help_text="CSS ratio, e.g. 16:9, 4:3, 1:1", max_length=10
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional max width in px", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional max height in px", null=True
                    ),
                ),
                (
                    "crop_mode",
                    models.CharField(
                        choices=[
                            ("cover", "Cover (fill, crop edges)"),
                            ("contain", "Contain (fit inside, letterbox)"),
                        ],
                        default="cover",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Image variant",
                "verbose_name_plural": "Image variants",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="image_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Display preset for this project's image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio.imagevariant",
            ),
        ),
    ]
