# Generated by Django 5.0 on 2026-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_imagevariant_and_project_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagevariant",
            name="allow_zoom",
            field=models.BooleanField(
                default=True,
                help_text="Enable CSS scale on hover (only when site motion is enabled)",
            ),
        ),
        migrations.AddField(
            model_name="imagevariant",
            name="background_color",
            field=models.CharField(
                blank=True,
                help_text='Background color for CONTAIN mode letterboxing, e.g. "#f0f0f0"',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="imagevariant",
            name="border_radius",
            field=models.CharField(
                blank=True,
                help_text='Custom border radius for ROUNDED shape, e.g. "12px" or "1rem"',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="imagevariant",
            name="object_position",
            field=models.CharField(
                default="center center",
                help_text='CSS object-position to control crop focus, e.g. "50% 20%"',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="imagevariant",
            name="shape",
            field=models.CharField(
                choices=[
                    ("rect", "Rectangle (no rounding)"),
                    ("rounded", "Rounded corners"),
                    ("circle", "Circle (forces 1:1 ratio)"),
                ],
                default="rect",
                help_text="RECT: no rounding; ROUNDED: custom radius; CIRCLE: fully round (1:1)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="imagevariant",
            name="crop_mode",
            field=models.CharField(
                choices=[
                    ("cover", "Cover (fill, crop edges)"),
                    ("contain", "Contain (fit inside, letterbox)"),
                ],
                default="cover",
                help_text="COVER crops to fill; CONTAIN fits fully with possible letterboxing",
                max_length=10,
            ),
        ),
    ]
