# Generated by Django 5.0 on 2026-02-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_imagevariant_shape_crop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Certification name", max_length=200),
                ),
                (
                    "issuer",
                    models.CharField(help_text="Issuing organization", max_length=200),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expires_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=200)),
                (
                    "credential_url",
                    models.URLField(blank=True, help_text="Verification URL"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/files/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/images/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EducationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Degree or program name", max_length=200
                    ),
                ),
                (
                    "institution",
                    models.CharField(help_text="School or university", max_length=200),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "url",
                    models.URLField(blank=True, help_text="Institution or program URL"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="education/files/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="education/images/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Education entry",
                "verbose_name_plural": "Education entries",
                "ordering": ["order", "id"],
            },
        ),
    ]
