# Generated by Django 5.0 on 2026-02-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_certification_educationentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certifications",
                to="portfolio.category",
            ),
        ),
        migrations.AddField(
            model_name="educationentry",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="education_entries",
                to="portfolio.category",
            ),
        ),
    ]
