# Generated by Django 5.0 on 2026-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_certification_category_educationentry_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_featured_projects_count",
            field=models.PositiveIntegerField(
                default=3,
                help_text="How many featured projects to show on the homepage",
            ),
        ),
    ]
