# Generated by Django 5.0 on 2026-02-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_sitesetting_homepage_featured_projects_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="projects/attachments/"
                    ),
                ),
                ("external_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("visible", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project attachment",
                "verbose_name_plural": "Project attachments",
                "ordering": ["order", "id"],
            },
        ),
    ]
