# Generated by Django 5.0 on 2026-02-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_projectattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="homepage_featured_category_blocks_count",
            field=models.PositiveIntegerField(
                default=3,
                help_text="How many category blocks to show in Featured Projects on homepage",
            ),
        ),
    ]
