# Generated by Django 5.0 on 2026-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_sitesetting_homepage_featured_category_blocks_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/images/"
            ),
        ),
    ]
