# Generated by Django 5.0 on 2026-02-11 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0022_layoutprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="layoutprofile",
            name="accent_color",
            field=models.CharField(
                blank=True,
                help_text="Override --accent (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="bg_color",
            field=models.CharField(
                blank=True,
                help_text="Override --bg (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="border_color",
            field=models.CharField(
                blank=True,
                help_text="Override --border (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="font_stack",
            field=models.CharField(
                choices=[
                    ("system", "System (default)"),
                    ("sans", "Sans-serif (Inter / Helvetica)"),
                    ("serif", "Serif (Georgia / Merriweather)"),
                ],
                default="system",
                help_text="Font family preset",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="headshot_image",
            field=models.ImageField(
                blank=True,
                help_text="Override headshot photo",
                null=True,
                upload_to="profiles/headshot/",
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                help_text="Override hero background image",
                null=True,
                upload_to="profiles/hero/",
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="muted_text_color",
            field=models.CharField(
                blank=True,
                help_text="Override --text-muted (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="surface_color",
            field=models.CharField(
                blank=True,
                help_text="Override --surface (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="token_text_color",
            field=models.CharField(
                blank=True,
                help_text="Override --text (hex)",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid hex color, e.g. #00aaff",
                        regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="layoutprofile",
            name="type_scale",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("compact", "Compact"),
                    ("spacious", "Spacious"),
                ],
                default="default",
                help_text="Type size scale",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="layoutprofile",
            name="template_variant",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("modern_saas", "Modern SaaS"),
                    ("executive_minimal", "Executive Minimal"),
                    ("data_lab", "Data Lab"),
                    ("split_screen", "Split Screen"),
                    ("magazine_editorial", "Magazine Editorial"),
                    ("card_dashboard", "Card Dashboard"),
                    ("glass_modern", "Glass Modern"),
                    ("bold_branding", "Bold Branding"),
                    ("timeline_pro", "Timeline Pro"),
                    ("technical_research", "Technical Research"),
                ],
                default="default",
                help_text="Template layout variant",
                max_length=30,
            ),
        ),
    ]
