# Generated by Django 5.0 on 2026-02-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0023_design_tokens_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="hero_label",
            field=models.CharField(
                blank=True,
                help_text="Small eyebrow label above the name, e.g. 'Personal Site'",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="hero_roles",
            field=models.CharField(
                blank=True,
                help_text="Pipe-separated roles, e.g. 'Data Analyst | Data Scientist | BI'",
                max_length=255,
            ),
        ),
    ]
