# Generated by Django 5.0 on 2026-02-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0024_hero_identity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Freeform project notes displayed on the detail page",
            ),
        ),
    ]
